#!/bin/bash
# =============================================================================
# setup_env.sh
# ------------
# Configures the environment for the "Launch My Kebap" ADK agent project.
#
# This script:
#   1. Enables required Google Cloud APIs (Maps, BigQuery, remote MCP).
#   2. Creates a restricted Google Maps Platform API key with the necessary
#      APIs enabled (Places, Directions, Geocoding, Maps JavaScript).
#   3. Writes a .env file in the adk_agent/ directory with all required
#      environment variables for the Python agent.
#
# Usage:
#   cd launchmykebap/setup
#   bash setup_env.sh
# =============================================================================

set -e

PROJECT_ID=$(gcloud config get-value project)
KEY_DISPLAY_NAME="kebap-agent-maps-key"

echo "================================================================"
echo "  Launch My Kebap – Environment Setup"
echo "  Project: $PROJECT_ID"
echo "================================================================"

# ── Step 1: Enable required Google Cloud APIs ────────────────────────────────
echo "[1/3] Enabling Google Cloud APIs..."
gcloud services enable \
    maps-backend.googleapis.com \
    places-backend.googleapis.com \
    directions-backend.googleapis.com \
    geocoding-backend.googleapis.com \
    bigquery.googleapis.com \
    bigquerymigration.googleapis.com \
    bigquerystorage.googleapis.com \
    storage.googleapis.com \
    apikeys.googleapis.com \
    aiplatform.googleapis.com \
    --project="$PROJECT_ID"
echo "      APIs enabled. Waiting 10 seconds for enablement to propagate..."
sleep 10

# ── Step 2: Create a restricted Maps API key ─────────────────────────────────
echo "[2/3] Creating restricted Maps Platform API key..."
MAPS_API_KEY=$(gcloud services api-keys create \
    --display-name="$KEY_DISPLAY_NAME" \
    --api-target=service=maps-backend.googleapis.com \
    --api-target=service=places-backend.googleapis.com \
    --api-target=service=directions-backend.googleapis.com \
    --api-target=service=geocoding-backend.googleapis.com \
    --format="value(keyString)" \
    --project="$PROJECT_ID" || \
    # If key already exists, retrieve it by display name
    gcloud services api-keys list \
        --filter="displayName=$KEY_DISPLAY_NAME" \
        --format="value(keyString)" \
        --project="$PROJECT_ID" | head -1)

if [ -z "$MAPS_API_KEY" ]; then
    echo "ERROR: Could not create or retrieve Maps API key programmatically."
    read -p "Please enter your Google Maps Platform API Key manually: " MAPS_API_KEY
fi

if [ -z "$MAPS_API_KEY" ]; then
    echo "ERROR: Maps API Key cannot be empty."
    exit 1
fi
echo "      Maps API key ready."

# ── Step 3: Write .env file ──────────────────────────────────────────────────
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ENV_FILE="$SCRIPT_DIR/../adk_agent/mcp_kebap_app/.env"
mkdir -p "$(dirname "$ENV_FILE")"

echo "[3/3] Writing .env file to $ENV_FILE ..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup_env.sh — do NOT commit this file to version control.

# Enable Vertex AI (bypasses standard Gemini API Key requirement)
GOOGLE_GENAI_USE_VERTEXAI=1
GOOGLE_CLOUD_LOCATION=global

# Google Cloud project ID (used for BigQuery job billing)
GOOGLE_CLOUD_PROJECT=$PROJECT_ID

# Restricted Google Maps Platform API key
# Enabled APIs: Maps Backend, Places, Directions, Geocoding
MAPS_API_KEY=$MAPS_API_KEY

# BigQuery dataset containing the Gaziantep market intelligence tables
BIGQUERY_DATASET=mcp_kebap
EOF

echo "      .env file written."
echo "================================================================"
echo "  Environment setup complete!"
echo "  Next steps:"
echo "    1. cd ../setup && bash setup_bigquery.sh"
echo "    2. cd ../adk_agent && adk web mcp_kebap_app"
echo "================================================================"
